name: Update Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行

jobs:
  update-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Fetch GitHub contributions
        run: node fetch-contributions.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add .
          git commit -m "Update contributions"
          git push

