name: Update Contributions Data

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
    - main

jobs:
  update-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Updated to the latest version as of my last training data

      - name: Set Up Node.js
        uses: actions/setup-node@v3 # Updated to the latest version and correct usage of node-version
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Generate Contributions Data
        run: npm run generate-contributions

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.bot }}
        run: |
          git config --global user.name "HanryYu"
          git config --global user.email "fishion@outlook.com"
          git add date.json
          git commit -m "Update contributions data"
          git push
